### ISSUE TITLE
Filter tree

### ISSUE THREAD

**Issue by Vrolf** [hassanh12/2a-sosialia#13]

**Comment by Isakkm** [comment]
### vi må fikse et fungerende filter

har ikke erfaring med filter, men kanskje vi kan gi div-ene en class med kategorien dens i makeEventCards()
https://github.com/hassanh12/2a-sosialia/blob/bd73c0081df2fa9ecfba90d213a2d9ed89a7a3d7/hovedside.html#L92-L97
altså:
```
let CATEGORY = object.category  
eventDiv.setAttribute('class', 'CATEGORY  events elementBakgrunnsfarge') 
```


 med det kan vi forhåpentligvis sette `display: none` på divene uten riktig kategori

 eller kanskje reset `"main"` div og deretter kjøre `makeEventCards()` på nytt og _**bare lage event med riktig kategori**_

**Comment by Vrolf** [comment]
Ja, det fungerer bra. Som vi disukterte er det vanskelig å få laget et bra filter system. Men det du foreslår høres veldig bra ut
